language: node_js
os:
  - linux
node_js: 9.5.0
branches:
  only:
  - master
  - develop

install:
  - yarn
script:
  - yarn lint
  - yarn build

cache:
  yarn: true
  directories:
    - node_modules
before_deploy:
  - cd dist
  - touch CNAME
  - CNAME << "preview.arkavidia.id"
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: develop
  file: dist/
  repo: arkavidia5/preview
  keep-history: true
  target_branch: master


