language: node_js
branches:
  only:
    - master
    - develop
os:
  - linux
node_js: 9.5.0

install:
  - yarn
script:
  - yarn lint
  - yarn build
cache:
  yarn: true
  directories:
    - node_modules
